### ISSUE TITLE
TypeError: this.updaters is not iterable

### ISSUE THREAD

**Issue by ArmaghanRaza** [EOSIO/demux-js#105]
at ActionHandler.<anonymous> (/home/moon/demux/node_modules/demux/dist/AbstractActionHandler.js:74:44)
    at Generator.next (<anonymous>)
    at /home/moon/demux/node_modules/demux/dist/AbstractActionHandler.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/moon/demux/node_modules/demux/dist/AbstractActionHandler.js:3:12)
    at ActionHandler.runUpdaters (/home/moon/demux/node_modules/demux/dist/AbstractActionHandler.js:71:16)
    at ActionHandler.<anonymous> (/home/moon/demux/node_modules/demux/dist/AbstractActionHandler.js:103:24)
    at Generator.next (<anonymous>)
    at /home/moon/demux/node_modules/demux/dist/AbstractActionHandler.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/moon/demux/node_modules/demux/dist/AbstractActionHandler.js:3:12)
    at ActionHandler.handleActions (/home/moon/demux/node_modules/demux/dist/AbstractActionHandler.js:101:16)
    at ActionHandler.<anonymous> (/home/moon/demux/node_modules/demux/dist/AbstractActionHandler.js:61:28)
    at Generator.next (<anonymous>)
    at /home/moon/demux/node_modules/demux/dist/AbstractActionHandler.js:7:71
    at new Promise (<anonymous>)

**Comment by chris-allnutt** [comment]
@ArmaghanRaza please provide some sample code that causes this.  The error trace isn't useful without the context it was executed in.

**Comment by jeffreyssmith2nd** [comment]
Closing due to inactivity.
