### ISSUE TITLE
can't run examples

### ISSUE THREAD

**Issue by bitcoiners** [EOSIO/demux-js#15]
Tried running
```
$ ./run-example.sh
module.js:557
    throw err;
    ^

Error: Cannot find module '/root/demux-js/examples/index.js'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:618:3

```

**Comment by bitcoiners** [comment]
nevermind found out that I need to add example name to command.

**Comment by harshitgupta** [comment]
For those who are facing similar issues or having trouble running the example, just do the following:

```
- git clone https://github.com/EOSIO/demux-js.git
- cd demux-js
- yarn (or npm install)
- yarn example eos-transfers
```

Its works like a charm.
