### ISSUE TITLE
running example results in a fork detection.

### ISSUE THREAD

**Issue by bitcoiners** [EOSIO/demux-js#16]
yarn example eos-transfers

```
...
State updated:
 {
  "volumeBySymbol": {
    "EOS": 590.2256
  },
  "totalTransfers": 14,
  "indexState": {
    "blockNumber": 8655579,
    "blockHash": "008412db36228bc3cce31eeede203a8ba7962f8c8d133de8438182464ab988b1"
  }
}
!! Fork detected !!
✓ BLOCK 8655587 MATCH:
  expected: 008412e2859f7530e9f130837b65f28ce0881a209013afae86a91579fd90aab4
  received: 008412e2859f7530e9f130837b65f28ce0881a209013afae86a91579fd90aab4
Rewinding 1 blocks to block (8655587)...
(node:2230) UnhandledPromiseRejectionWarning: TypeError: this.rollbackTo is not a function
    at ObjectActionHandler.<anonymous> (/root/demux-js/dist/demux/handlers/AbstractActionHandler.js:39:28)
    at Generator.next (<anonymous>)
    at /root/demux-js/dist/demux/handlers/AbstractActionHandler.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/root/demux-js/dist/demux/handlers/AbstractActionHandler.js:3:12)
    at ObjectActionHandler.handleBlock (/root/demux-js/dist/demux/handlers/AbstractActionHandler.js:37:16)
    at BaseActionWatcher.<anonymous> (/root/demux-js/dist/demux/watchers/BaseActionWatcher.js:45:75)
    at Generator.next (<anonymous>)
    at fulfilled (/root/demux-js/dist/demux/watchers/BaseActionWatcher.js:4:58)
    at <anonymous>
(node:2230) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:2230) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 109.09s.
```

**Comment by bitcoiners** [comment]
Ran again. This time got a new error:

```
State updated:
 {
  "volumeBySymbol": {
    "EOS": 981.0065999999999
  },
  "totalTransfers": 8,
  "indexState": {
    "blockNumber": 8659778,
    "blockHash": "00842342aa2868436b3671933aa41e4c3eb720f2370d52e576d0f93b61a54716"
  }
}
(node:2395) UnhandledPromiseRejectionWarning: StatusCodeError: 500 - {"code":500,"message":"Internal Service Error","error":{"code":3100002,"name":"unknown_block_exception","what":"Unknown block","details":[{"message":"Could not find block: 8659783","file":"chain_plugin.cpp","line_number":1276,"method":"get_block"}]}}
    at new StatusCodeError (/root/demux-js/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/root/demux-js/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/root/demux-js/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/root/demux-js/node_modules/request/request.js:185:22)
    at Request.emit (events.js:159:13)
    at Request.<anonymous> (/root/demux-js/node_modules/request/request.js:1157:10)
    at Request.emit (events.js:159:13)
    at IncomingMessage.<anonymous> (/root/demux-js/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:254:19)
    at IncomingMessage.emit (events.js:164:20)
(node:2395) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2395) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 84.70s.
```

**Comment by flux627** [comment]
The example project currently does not support rollbacks from forks. This should probably just ignore forks, and continue as if it didn't happen. That may lead to data inconsistency, but it's probably fine for the example.

**Comment by MrToph** [comment]
This is super annoying as it happens after minutes. How do you make a correct rollback? I tried using a `noop` in `rollbackTo` but after some time I get this error:

```
Error: Rollback history has been exhausted, and no rollback exhaustion handling has been implemented.
```

**Comment by kasperfish** [comment]
just got the same issue
![image](https://user-images.githubusercontent.com/5130772/45318483-6a8c1d00-b53d-11e8-8eb2-7b7c9a30db39.png)

**Comment by kiettran307** [comment]
Got the same issue 
<img width="777" alt="screen shot 2018-09-18 at 4 13 36 pm" src="https://user-images.githubusercontent.com/22650079/45677252-ef8abe00-bb5d-11e8-8012-44717c6294c6.png">
