### ISSUE TITLE
UnhandledPromiseRejectionWarning: StatusCodeError: 500

### ISSUE THREAD

**Issue by harshitgupta** [EOSIO/demux-js#17]
Hi, 

I pulled the code and ran the example. Worked fine the first time and failed afterwards due to unhandled promise.

```
➜  demux-js git:(develop) yarn example eos-transfers
yarn run v1.1.0
$ ./run-example.sh "eos-transfers"
(node:6496) UnhandledPromiseRejectionWarning: StatusCodeError: 500 - {"code":500,"message":"Internal Service Error","error":{"code":3100002,"name":"unknown_block_exception","what":"Unknown block","details":[{"message":"Could not find block: 8656566","file":"chain_plugin.cpp","line_number":1276,"method":"get_block"}]}}
    at new StatusCodeError (/Users/harshitgupta/Developer/demux-js/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/Users/harshitgupta/Developer/demux-js/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/Users/harshitgupta/Developer/demux-js/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/Users/harshitgupta/Developer/demux-js/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/Users/harshitgupta/Developer/demux-js/node_modules/request/request.js:1157:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/Users/harshitgupta/Developer/demux-js/node_modules/request/request.js:1079:12)
(node:6496) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6496) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✨  Done in 13.65s.
```

**Comment by flux627** [comment]
Thanks for the report! This occurs when we query `get_info` to retrieve the head block number, and then upon querying `get_block` for said block number, it doesn't exist. We are still investigating the conditions for when this occurs, but regardless of the reason this should be handled.

**Comment by jafri** [comment]
This happens while following blocks, tried on 5 different API endpoints.

The library is essentially not useable with this bug.

**Comment by flux627** [comment]
Since we have moved the code in question to [EOSIO/demux-js-eos](https://github.com/EOSIO/demux-js-eos), I am closing this. Feel free to open a new issue there.
