### ISSUE TITLE
Some tests are failing.

### ISSUE THREAD

**Issue by jeffreyssmith2nd** [EOSIO/demux-js#28]
Tests in the MassiveActionHandler are failing when run locally or through travis-ci.
``` PASS  src/demux/readers/eos/NodeosBlock.test.ts
 PASS  src/demux/handlers/AbstractActionHandler.test.ts
 PASS  src/demux/readers/eos/NodeosActionReader.test.ts
 FAIL  src/demux/handlers/postgres/MassiveActionHandler.test.ts (15.831s)
  ● MassiveActionHandler › populates database correctly

    error: syntax error at or near "is_replay"

      at Connection.Object.<anonymous>.Connection.parseE (node_modules/pg/lib/connection.js:553:11)
      at Connection.Object.<anonymous>.Connection.parseMessage (node_modules/pg/lib/connection.js:378:19)
      at Socket.<anonymous> (node_modules/pg/lib/connection.js:119:22)

  ● MassiveActionHandler › populates database correctly

    error: relation "public.task" does not exist

      at Connection.Object.<anonymous>.Connection.parseE (node_modules/pg/lib/connection.js:553:11)
      at Connection.Object.<anonymous>.Connection.parseMessage (node_modules/pg/lib/connection.js:378:19)
      at Socket.<anonymous> (node_modules/pg/lib/connection.js:119:22)

  ● MassiveActionHandler › populates database correctly

    TypeError: Cannot read property 'findOne' of undefined

      42 |
      43 |   protected async loadIndexState(): Promise<IndexState> {
    > 44 |     const { blockNumber, blockHash } = await this.massiveInstance._index_state.findOne({ id: 0 })
      45 |     if (blockNumber && blockHash) {
      46 |       return { blockNumber, blockHash }
      47 |     }

      at MassiveActionHandler.<anonymous> (src/demux/handlers/postgres/MassiveActionHandler.ts:44:80)
      at src/demux/handlers/postgres/MassiveActionHandler.ts:24:71
      at Object.<anonymous>.__awaiter (src/demux/handlers/postgres/MassiveActionHandler.ts:4:12)
      at MassiveActionHandler.loadIndexState (src/demux/handlers/postgres/MassiveActionHandler.ts:69:16)
      at MassiveActionHandler.<anonymous> (src/demux/handlers/AbstractActionHandler.ts:33:97)
      at src/demux/handlers/AbstractActionHandler.ts:24:71
      at Object.<anonymous>.__awaiter (src/demux/handlers/AbstractActionHandler.ts:4:12)
      at MassiveActionHandler.handleBlock (src/demux/handlers/AbstractActionHandler.ts:51:16)
      at Object.<anonymous> (src/demux/handlers/postgres/MassiveActionHandler.test.ts:52:25)
      at fulfilled (src/demux/handlers/postgres/MassiveActionHandler.test.ts:9:32)

Test Suites: 1 failed, 3 passed, 4 total
Tests:       1 failed, 9 passed, 10 total```

**Comment by flux627** [comment]
These classes were removed from the repo (however I think they were fixed beforehand). If this is is still an issue we can reopen on EOSIO/demux-js-postgres
