### ISSUE TITLE
there is no demux-eos version 1.0.1

### ISSUE THREAD

**Issue by Thomas55777** [EOSIO/demux-js#41]
With the most recent commit 92698a9e81e70d588e24746c07df34049cee5dcc it looks like it is now referencing demux-eos 1.0.1 however this package is not available in npm.  Currently the latest version in npm is 0.0.1-hotfix

https://www.npmjs.com/package/demux-eos

**Comment by jeffreyssmith2nd** [comment]
https://github.com/EOSIO/demux-js-eos/pull/4

**Comment by Thomas55777** [comment]
Thank you for quick update.  However now I am getting the following when I try to run:

```
> node index.js

...EOS/demux-js/examples/eos-transfers/ObjectActionHandler.js:1
(function (exports, require, module, __filename, __dirname) { const { handlers: { AbstractActionHandler } } = require("demux")
                                                                                  ^

TypeError: Cannot destructure property `AbstractActionHandler` of 'undefined' or 'null'.
    at Object.<anonymous> (/mnt/c/Users/TPowers/Documents/GitHub/EOS/demux-js/examples/eos-transfers/ObjectActionHandler.js:1:71)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/mnt/c/Users/TPowers/Documents/GitHub/EOS/demux-js/examples/eos-transfers/index.js:3:29)
    at Module._compile (module.js:652:30)
```

**Comment by jeffreyssmith2nd** [comment]
https://github.com/EOSIO/demux-js/releases/tag/1.0.2

The import style changed in 1.0.2, see above for the new format.

**Comment by Thomas55777** [comment]
I think I see what happened, it seems that the most recent version hasn't been committed to the repository yet.  The release 1.0.2 works for me but the git repo has the older code.  

Thank you for you help, this is an excellent project.
